--Add Here datas 
INSERT INTO PAYS (ID, VERSION, NOM) VALUES (1, 1.0, 'France');
INSERT INTO PAYS (ID, VERSION, NOM) VALUES (2, 1.0, 'United Kingdom');

INSERT INTO VILLE (ID, VERSION, NOM, PAYS_ID) VALUES (1, 1.0, 'Paris', 1);
INSERT INTO VILLE (ID, VERSION, NOM, PAYS_ID) VALUES (2, 1.0, 'Lyon', 1);
INSERT INTO VILLE (ID, VERSION, NOM, PAYS_ID) VALUES (3, 1.0, 'Marseille', 1);
INSERT INTO VILLE (ID, VERSION, NOM, PAYS_ID) VALUES (4, 1.0, 'London', 2);