version: '2'
services:
    resanet:
        image: resanet-01-zenika:0.0-SNAPSHOT
        ports:
           - "127.0.0.1:8080:8000"
        depends_on:
           - resanet-db
    resanet-db:
        image: resanet-01-db:0.0-SNAPSHOT
        ports:
            - "127.0.0.1:8082:1521"
            - "127.0.0.1:81:81"
        volumes:
            - ./h2-data:/opt/h2-data

