--Add Here datas 
INSERT INTO PAYS (ID, VERSION, NOM) VALUES (1, 1.0, 'France');
INSERT INTO PAYS (ID, VERSION, NOM) VALUES (2, 1.0, 'United Kingdom');

INSERT INTO VILLE (ID, VERSION, NOM, PAYS_ID) VALUES (1, 1.0, 'Paris', 1);
INSERT INTO VILLE (ID, VERSION, NOM, PAYS_ID) VALUES (2, 1.0, 'Lyon', 1);
INSERT INTO VILLE (ID, VERSION, NOM, PAYS_ID) VALUES (3, 1.0, 'Marseille', 1);
INSERT INTO VILLE (ID, VERSION, NOM, PAYS_ID) VALUES (4, 1.0, 'London', 2);

INSERT INTO TRANSPORT (DTYPE, ID, VERSION, DATE_DEPART, HEURE_ARRIVEE, HEURE_DEPART, NB_SIEGES_DISPO, NB_SIEGES_TOTAL, PRIX, NB_WAGONS, VOITURE_BAR, COMPAGNIE, TYPE_APPAREIL, VILLE_A, VILLE_D) VALUES ('Train', 1, 1.0, '2016-08-19', '16h', '19h', 42, 142, 40.0, 5, false, 'SNCF', 'Train', 1, 3);
INSERT INTO TRANSPORT (DTYPE, ID, VERSION, DATE_DEPART, HEURE_ARRIVEE, HEURE_DEPART, NB_SIEGES_DISPO, NB_SIEGES_TOTAL, PRIX, NB_WAGONS, VOITURE_BAR, COMPAGNIE, TYPE_APPAREIL, VILLE_A, VILLE_D) VALUES ('Train', 2, 1.0, '2016-08-17', '17h', '20h', 42, 142, 40.0, 5, false, 'SNCF', 'Train', 2, 3);
INSERT INTO TRANSPORT (DTYPE, ID, VERSION, DATE_DEPART, HEURE_ARRIVEE, HEURE_DEPART, NB_SIEGES_DISPO, NB_SIEGES_TOTAL, PRIX, NB_WAGONS, VOITURE_BAR, COMPAGNIE, TYPE_APPAREIL, VILLE_A, VILLE_D) VALUES ('Train', 3, 1.0, '2016-08-22', '18h', '21h', 42, 142, 40.0, 5, false, 'SNCF', 'Train', 3, 1);
INSERT INTO TRANSPORT (DTYPE, ID, VERSION, DATE_DEPART, HEURE_ARRIVEE, HEURE_DEPART, NB_SIEGES_DISPO, NB_SIEGES_TOTAL, PRIX, NB_WAGONS, VOITURE_BAR, COMPAGNIE, TYPE_APPAREIL, VILLE_A, VILLE_D) VALUES ('Train', 4, 1.0, '2016-08-13', '16h', '19h', 42, 142, 40.0, 5, false, 'SNCF', 'Train', 1, 2);
INSERT INTO TRANSPORT (DTYPE, ID, VERSION, DATE_DEPART, HEURE_ARRIVEE, HEURE_DEPART, NB_SIEGES_DISPO, NB_SIEGES_TOTAL, PRIX, NB_WAGONS, VOITURE_BAR, COMPAGNIE, TYPE_APPAREIL, VILLE_A, VILLE_D) VALUES ('Train', 5, 1.0, '2016-08-19', '19h', '22h', 42, 142, 40.0, 5, false, 'SNCF', 'Train', 1, 3);
INSERT INTO TRANSPORT (DTYPE, ID, VERSION, DATE_DEPART, HEURE_ARRIVEE, HEURE_DEPART, NB_SIEGES_DISPO, NB_SIEGES_TOTAL, PRIX, NB_WAGONS, VOITURE_BAR, COMPAGNIE, TYPE_APPAREIL, VILLE_A, VILLE_D) VALUES ('Train', 6, 1.0, '2016-08-19', '17h', '20h', 42, 142, 40.0, 5, false, 'SNCF', 'Train', 1, 3);